### ISSUE TITLE
Implement apple authentication

### ISSUE THREAD

**Issue by muslimomar** [RCDD-202203-TUR-BEW/backend-capstone-turkey-teach-kids#11]
## Tasks:

- Implement Apple authentication (route should start with `/auth`)
- Add documentation

**Comment by dilarafirtina** [comment]
Hi @muslimomar,  for implementing sign in with apple, according to the articles and npm packages * I read, I should be enrolled in Apple Developer Program which costs 679 liras. Is there any other way for this? 

*https://www.mongodb.com/docs/atlas/app-services/authentication/apple/
*https://www.passportjs.org/packages/passport-appleid/

**Comment by dilarafirtina** [comment]
I cannot solve the issue because I don't have a MAC
